apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myservice-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: myservice.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myservice-service
            port:
              name: http
      - path: /myservice2
        pathType: Prefix
        backend:
          service:
            name: myservice2-service
            port:
              name: http